---
- name: Verify web server
  hosts: all
  tasks:
    - name: Wait for the web server to start
      ansible.builtin.wait_for:
        port: 8096
        delay: 10
        timeout: 30

    - name: Verify that the web server is serving content
      ansible.builtin.uri:
        url: http://localhost:8096/health
        return_content: true
      register: health_content

    - name: Gather Jellyfin related web content
      ansible.builtin.uri:
        url: http://localhost:8096/web/#/wizardstart.html
        return_content: true
      register: jellyfin_content

    - name: Check if the web server is up
      ansible.builtin.assert:
        that:
          - "'Healthy' in health_content.content"
          - "'Jellyfin' in jellyfin_content.content"
